# Generated by Django 5.0 on 2023-12-25 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomType', models.CharField(default='single Room', max_length=100)),
                ('roomNumber', models.IntegerField(default='101', unique=True)),
                ('roomDescription', models.TextField(default='Room description')),
                ('roomImage', models.ImageField(upload_to='img/')),
                ('roomStatus', models.IntegerField(default=1)),
                ('roomPrice', models.FloatField(default=0.0)),
            ],
        ),
    ]
