# Generated by Django 5.0 on 2023-12-16 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomName', models.CharField(blank=True, max_length=50)),
                ('roomType', models.CharField(default='1 bed', max_length=100)),
                ('roomNumber', models.IntegerField(default='101')),
                ('roomDescription', models.TextField(default='Room description')),
                ('roomImage', models.ImageField(upload_to='img/')),
                ('roomStatus', models.IntegerField()),
                ('roomPrice', models.FloatField(default=0.0)),
            ],
        ),
    ]
