# Generated by Django 5.0 on 2023-12-19 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='roomStatus',
            field=models.IntegerField(default=1),
        ),
    ]
