# Generated by Django 5.0 on 2023-12-26 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_alter_room_roomstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='roomStatus',
            field=models.CharField(choices=[('Not Available', 'Not Available'), ('Available', 'Available')], default='Available', max_length=20),
        ),
    ]
