# Generated by Django 5.0 on 2023-12-19 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('date_from', models.DateTimeField(auto_now_add=True)),
                ('date_to', models.DateTimeField(auto_now=True)),
                ('children', models.IntegerField()),
                ('adult', models.IntegerField()),
                ('room', models.IntegerField(default=1)),
            ],
        ),
    ]
